### PR TITLE
Adding I2C custom Pins capability

### PR DESCRIPTION
**Pull request by boseji**
In ESP8266 we can actually change the default I2C pins similarly in DUE and STM32.
Hence this patch contains the added functionality to initialise the class `MD_DS1307` with alternate I2C pins.
Also added is an additional initialisation function to both class constructors.
This is to keep the variable initialisation common to both.
We are not sure how to generate the new documentation, but we have written the required comments.
Kindly take this forward.

### CODE REVIEW

**Comment by MajicDesigns** [comment]
As you point out, this change is only due to the ESP8266 having this capability. The code that uses the alternative wire.begin(sca, scl) needs to be isolated in an #ifdef segment for the type of hardware. This syntax does not exist for other hardware platforms and would cause compile errors for most users. Please amend and resubmit.

FYI, the documentation is generated using doxygen.

**Comment by MajicDesigns** [comment]
As you point out, this change is only due to the ESP8266, Due, etc having this capability. The code that uses the alternative wire.begin(sca, scl) needs to be isolated in an #ifdef segment for the types of hardware that support this. The syntax does not seem to be valid for other hardware platforms and would cause compile errors. Please amend and resubmit.

FYI, the documentation is generated using doxygen

**Comment by MajicDesigns** [comment]
Ignore previous comment. Looks like the library code has changed but they have not updated the manual pages on arduino.cc.

**Comment by boseji** [comment]
*Your library was really a great help to me*, so I thought it would be natural to contribute and help.

Currently I am using the Arduino v1.6.21 package. They had updated this facility.
Also from the ESP8266 Arduino v2.4.0 we got this available.
So for compatibility would be alright.

I am not sure of how to generate the dox.
Reading a bit of the Doxygen its a nice one would be good for my project too.
Thanks for sharing.

**Comment by MajicDesigns** [comment]
If you select Arduino Uno and try to compile the test example, does it work on your system?

**Comment by boseji** [comment]
You are right to suspect.
On SAMD v1.6.18 the Constructors
```c
    TwoWire(SERCOM *s, uint8_t pinSDA, uint8_t pinSCL);
    void begin();
    void begin(uint8_t, bool enableGeneralCall = false);
``` 

On avr v1.6.21
```c
    TwoWire();
    void begin();
    void begin(uint8_t);
    void begin(int);
```

Looks like we need a special `#ifdef` after all.
I will update after the fix.

**Pull request merged**
